#!/bin/bash

ORACLE_PWD=$1

echo "Setting password for SYS and SYSTEM users..."
su -p oracle -c "$ORACLE_HOME/bin/sqlplus / as sysdba << EOF
      ALTER USER SYS IDENTIFIED BY "$ORACLE_PWD";
      ALTER USER SYSTEM IDENTIFIED BY "$ORACLE_PWD";
      exit;
EOF" > /dev/null 2>&1
